node('master'){
    stage 'Testing Conectivity'
        checkout scm
        sh '''for lines in `cat ./appBash/list.txt`
        do
            echo $lines
                done'''

     stage 'Start App'
        checkout scm
        def nodeHome = tool name: 'v5.10.0', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH="${env.PATH}:${nodeHome}/bin"
        sh './appNode/start_environment.sh'
}
